formatter: "markdown table"

version: "0.20.0"

settings:
  anchor: true
  default: true
  description: true
  required: true
  sensitive: true
  type: true

sections:
  hide:
    - modules
    - providers

sort:
  enabled: true
  by: required

output:
  file: README.md
  mode: inject