formatter: "markdown document"

version: ">= 0.20"

output:
  file: "README.md"
  mode: replace

sort:
  enabled: false

settings:
  anchor: true
  default: true
  escape: true
  hide-empty: true
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true

sections:
  hide:
    - data-sources

content: |-
  ![Beta Status](https://img.shields.io/badge/Status-Beta-yellow)

  # VKCS Network Terraform module
  A Terraform module for `Network` in VKCS.

  This modules makes it easy to setup virtual networking in VKCS.

  It supports creating:
  - router (optionally connected to the Internet)
  - networks
  - subnets of the networks (unconditionally attached to the router)
  - subnet routes

  It does not support:
  - virtual networking without a router
  - just a single router
  - network without subnets
  - subnets not attached to the router
  - router routes

  ## Usage
  ### Simple network with Internet access
  ```hcl
  {{ include "examples/simple/main.tf" }}
  ```

  ## Examples
  You can find examples in the [`examples`](./examples) directory on [GitHub](https://github.com/vk-cs/terraform-vkcs-network/tree/v0.0.1/examples).

  Running an example:
  - Clone [GitHub repository](https://github.com/vk-cs/terraform-vkcs-network) and checkout tag v0.0.1.
  - [Install Terraform](https://cloud.vk.com/docs/en/tools-for-using-services/terraform/quick-start). **Note**: You do not need `vkcs_provider.tf` to run module example.
  - [Init Terraform](https://cloud.vk.com/docs/en/tools-for-using-services/terraform/quick-start#terraform_initialization) from the example folder.
  - [Run Terraform](https://cloud.vk.com/docs/en/tools-for-using-services/terraform/quick-start#creating_resources_via_terraform) to create example resources.
  - Check example output and explore created resources with `terraform show`, management console, CLI and API requests.
  - Remove example resources with `terraform destroy -auto-approve --refresh=false`

  {{ .Requirements }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}
